### auth
POST https://keycloak.farmperspektiva.aeroidea.ru/auth/realms/Test/protocol/openid-connect/token
Content-Type: application/x-www-form-urlencoded
Accept: application/json

grant_type=password&client_id=focus&client_secret=d5d89a18-e76d-47da-af94-8dafb8c1c250&username={{username}}&password={{password}}

> {%
    client.test("Request executed successfully", function () {
        const type = response.contentType.mimeType
        client.assert(type === "application/json", "Expected 'application/json' but received '" + type + "'")
        client.assert(response.status === 200, "Response status is not 200")
        client.assert(response.body.hasOwnProperty("access_token"), "Dont have access_token")
    })

    client.global.set("access", response.body.access_token)
%}

###
GET    {{baseUrl}}/menus
Service-Code: {{service-code}}
Authorization: {{access}}

###
POST   {{baseUrl}}/menus
Content-Type: application/json
Service-Code: {{service-code}}
Authorization: {{access}}

{
    "name": "Верхнее меню 1",
    "code": "top"
}

> {%
    client.test("Request executed successfully", function () {
        const type = response.contentType.mimeType
        client.assert(type === "application/json", "Expected 'application/json' but received '" + type + "'")
        client.assert(response.status === 201, "Response status is not 201")
        client.assert(response.body.hasOwnProperty("id"), "Dont have id")
    })

    client.global.set("menu-id", response.body.id)
%}

###
GET    {{baseUrl}}/menus/{{menu-id}}
Service-Code: {{service-code}}
Authorization: {{access}}

###
PUT    {{baseUrl}}/menus/{{menu-id}}
Content-Type: application/json
Service-Code: {{service-code}}
Authorization: {{access}}

{
    "name": "Верхнее меню 1",
    "code": "top"
}

###
GET    {{baseUrl}}/menus/{{menu-id}}/items
Service-Code: {{service-code}}
Authorization: {{access}}

###
POST   {{baseUrl}}/menus/{{menu-id}}/items
Content-Type: application/json
Service-Code: {{service-code}}
Authorization: {{access}}

{
    "name": "Пункт меню 1",
    "url": "path-to-item",
    "parentMenuItemId": null,
    "additionalFields": [
        {
            "code": "color",
            "value": "#f00"
        }
    ]
}

> {%
    client.test("Request executed successfully", function () {
        const type = response.contentType.mimeType
        client.assert(type === "application/json", "Expected 'application/json' but received '" + type + "'")
        client.assert(response.status === 201, "Response status is not 201")
        client.assert(response.body.hasOwnProperty("id"), "Dont have id")
    })

    client.global.set("menu-item-id", response.body.id)
%}

###
GET    {{baseUrl}}/menus/{{menu-id}}/items/{{menu-item-id}}
Service-Code: {{service-code}}
Authorization: {{access}}

###
PUT    {{baseUrl}}/menus/{{menu-id}}/items/{{menu-item-id}}
Content-Type: application/json
Service-Code: {{service-code}}
Authorization: {{access}}

{
    "name": "Пункт меню 1",
    "url": "path-to-item",
    "parentMenuItemId": null,
    "additionalFields": [
        {
            "code": "color",
            "value": "#f00"
        }
    ]
}

###
POST   {{baseUrl}}/menus/{{menu-id}}/items/{{menu-item-id}}/move
Content-Type: application/json
Service-Code: {{service-code}}
Authorization: {{access}}

{
    "parentMenuItemId": null,
    "position": 2
}

###
DELETE {{baseUrl}}/menus/{{menu-id}}/items/{{menu-item-id}}
Service-Code: {{service-code}}
Authorization: {{access}}

###
DELETE {{baseUrl}}/menus/{{menu-id}}
Service-Code: {{service-code}}
Authorization: {{access}}