version: '3'

volumes:
  postgres_data:
    driver: local

services:
  postgres_keycloak:
    container_name: postgres_keycloak
    image: postgres
    ports:
      - 5444:5432
    volumes:
      - ./.docker/postgres/keycloak/postgres_data:/var/lib/postgresql/data
      - ./keycloak/dump_keycloak.sql:/keycloak/dump_keycloak.sql
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:legacy
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres_keycloak
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_SCHEMA: public
      DB_PASSWORD: password
      # Uncomment the line below if you want to specify JDBC parameters. The parameter below is just an example, and it shouldn't be used in production without knowledge. It is highly recommended that you read the PostgreSQL JDBC driver documentation in order to use it.
      #JDBC_PARAMS: "ssl=true"
    ports:
      - 8088:8080
    depends_on:
      - postgres_keycloak
  minio:
    container_name: minio
    image: minio/minio:latest
    volumes:
      - ./.docker/minio:/data
    ports:
      - "9005:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minio1234567890
      MINIO_ROOT_PASSWORD: minio1234567890
    command: server /data --console-address ":9001"

  createbuckets:
    container_name: createbuckets
    image: minio/mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc config host add local_minio http://minio:9000 minio1234567890 minio1234567890;
      /usr/bin/mc rm -r --force local_minio/content;
      /usr/bin/mc mb local_minio/content;
      /usr/bin/mc policy download local_minio/content;
      
      /usr/bin/mc rm -r --force local_minio/catalog;
      /usr/bin/mc mb local_minio/catalog;
      /usr/bin/mc policy download local_minio/catalog;
      
      /usr/bin/mc rm -r --force local_minio/orders;
      /usr/bin/mc mb local_minio/orders;
      /usr/bin/mc policy download local_minio/orders;
      
      /usr/bin/mc rm -r --force local_minio/users;
      /usr/bin/mc mb local_minio/users;
      /usr/bin/mc policy download local_minio/users;
      exit 0;
      "

  postgres_content:
    container_name: postgres_content
    ports:
      - "5403:5432"
    image: postgres
    volumes:
      - ./.docker/postgres/content/postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: content
      POSTGRES_USER: content
      POSTGRES_PASSWORD: content
        
  postgres_orders:
    container_name: postgres_orders
    ports:
      - "5405:5432"
    image: postgres
    volumes:
      - ./.docker/postgres/orders/postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: orders
      POSTGRES_USER: orders
      POSTGRES_PASSWORD: orders
      
  postgres_catalog:
    container_name: postgres_catalog
    ports:
      - "5406:5432"
    image: postgres
    volumes:
      - ./.docker/postgres/catalog/postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: catalog
      POSTGRES_USER: catalog
      POSTGRES_PASSWORD: catalog
      
  postgres_users:
    container_name: postgres_users
    ports:
      - "5407:5432"
    image: postgres
    volumes:
      - ./.docker/postgres/users/postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: users
      POSTGRES_USER: users
      POSTGRES_PASSWORD: users