version: '3'

volumes:
  postgres_data:
    driver: local

services:
  admin-ui:
    container_name: admin-ui
    build:
      context: ./admin-ui
      dockerfile: ./.docker/Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - env/common/.env.admin-ui
  admin-connector:
    container_name: admin-connector
    volumes:
      - ./app/:/app
    build:
      context: ./admin-connector
      dockerfile: ./.docker/Dockerfile
    ports:
      - "8081:8081"
    env_file:
      - env/common/.env.admin-connector
      - env/docker/.env.admin-connector

  dms1:
    container_name: dms1
    volumes:
      - ./app/:/app
    build:
      context: ./demo-service-1
      dockerfile: ./.docker/Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - env/common/.env.dms1
      - env/docker/.env.dms1
    depends_on:
      - minio
      - createbuckets
      - postgres_dms1

  postgres_keycloak:
    container_name: postgres_keycloak
    image: postgres
    ports:
      - 5444:5432
    volumes:
      - ./.docker/postgres/keycloak/postgres_data:/var/lib/postgresql/data
      - ./keycloak/dump_keycloak.sql:/keycloak/dump_keycloak.sql
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:legacy
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres_keycloak
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_SCHEMA: public
      DB_PASSWORD: password
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: Pa55w0rd
      # Uncomment the line below if you want to specify JDBC parameters. The parameter below is just an example, and it shouldn't be used in production without knowledge. It is highly recommended that you read the PostgreSQL JDBC driver documentation in order to use it.
      #JDBC_PARAMS: "ssl=true"
    ports:
      - 8088:8080
    depends_on:
      - postgres_keycloak
  minio:
    container_name: minio
    image: minio/minio:latest
    volumes:
      - ./.docker/minio:/data
    ports:
      - "9005:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minio1234567890
      MINIO_ROOT_PASSWORD: minio1234567890
    command: server /data --console-address ":9001"

  createbuckets:
    container_name: createbuckets
    image: minio/mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc config host add local_minio http://minio:9000 minio1234567890 minio1234567890;
      /usr/bin/mc rm -r --force local_minio/demo;
      /usr/bin/mc mb local_minio/demo;
      /usr/bin/mc policy download local_minio/demo;
      exit 0;
      "

  postgres_dms1:
    container_name: postgres_dms1
    ports:
      - "5401:5432"
    image: postgres
    volumes:
      - ./.docker/postgres/dms1/postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: dms1
      POSTGRES_USER: dms1
      POSTGRES_PASSWORD: dms1

  postgres_dms2:
    container_name: postgres_dms2
    ports:
      - "5402:5432"
    image: postgres
    volumes:
      - ./.docker/postgres/dms2/postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: dms2
      POSTGRES_USER: dms2
      POSTGRES_PASSWORD: dms2