goose-up:
	goose postgres "user=postgres password=postgres dbname=demo sslmode=disable" up
goose-down:
	goose postgres "user=postgres password=postgres dbname=demo sslmode=disable" down
goose-makefile:
	goose create create_table sql