### auth
POST http://127.0.0.1:8088/auth/realms/master/protocol/openid-connect/token
Content-Type: application/x-www-form-urlencoded
Accept: application/json

grant_type=password&client_id=focus&client_secret=wg4tu0juuDYombim5Ri7ZEVUR3TaPKrJ&username={{username}}&password={{password}}

> {%
    client.test("Request executed successfully", function () {
        const type = response.contentType.mimeType
        client.assert(type === "application/json", "Expected 'application/json' but received '" + type + "'")
        client.assert(response.status === 200, "Response status is not 200")
        client.assert(response.body.hasOwnProperty("access_token"), "Dont have access_token")
    })

    client.global.set("access", response.body.access_token)
%}

### получение краткого списка магазинов: неверный офсет
GET {{baseUrl}}/models-v2/{{product-model-code}}/fields/{{product-field-code}}?offset=-1&limit={{limit}}
Service-Code: {{service-code}}
Authorization: {{access}}

> {%
    client.test("Request executed successfully", function () {
        const type = response.contentType.mimeType
        client.assert(type === "application/json", "Expected 'application/json' but received '" + type + "'")
        client.assert(response.status === 400, "Response status is not 400")
        client.assert(response.body.code === 400, "code is not 400")
        client.assert(response.body.error === "Bad Request", "error is not Bad Request")
        client.assert(response.body.message === "Поле offset должно быть больше или равно 0.", "wrong message")
    })
%}

### получение краткого списка магазинов: неверный лимит
GET {{baseUrl}}/models-v2/{{product-model-code}}/fields/{{product-field-code}}?offset={{offset}}&limit=-1
Service-Code: {{service-code}}
Authorization: {{access}}

> {%
    client.test("Request executed successfully", function () {
        const type = response.contentType.mimeType
        client.assert(type === "application/json", "Expected 'application/json' but received '" + type + "'")
        client.assert(response.status === 400, "Response status is not 400")
        client.assert(response.body.code === 400, "code is not 400")
        client.assert(response.body.error === "Bad Request", "error is not Bad Request")
        client.assert(response.body.message === "Поле limit должно быть больше или равно 1.", "wrong message")
    })
%}

### получение краткого списка магазинов: неверный sort order
GET {{baseUrl}}/models-v2/{{product-model-code}}/fields/{{product-field-code}}?offset=-1&limit=10000
Service-Code: {{service-code}}
Authorization: {{access}}

> {%
    client.test("Request executed successfully", function () {
        const type = response.contentType.mimeType
        client.assert(type === "application/json", "Expected 'application/json' but received '" + type + "'")
        client.assert(response.status === 400, "Response status is not 400")
        client.assert(response.body.code === 400, "code is not 400")
        client.assert(response.body.error === "Bad Request", "error is not Bad Request")
        client.assert(response.body.message === "Поле offset должно быть больше или равно 0. Поле limit должно быть меньше или равно 100.", "wrong message")
    })
%}

### products short list
GET {{baseUrl}}/models-v2/{{product-model-code}}/elements?fields=sdfsdf&offset={{offset}}&limit={{limit}}
Service-Code: {{service-code}}
Authorization: {{access}}

> {%
    client.test("Request executed successfully", function () {
        const type = response.contentType.mimeType
        client.assert(type === "application/json", "Expected 'application/json' but received '" + type + "'")
        client.assert(response.status === 400, "Response status is not 400")
        client.assert(response.body.code === 400, "code is not 400")
        client.assert(response.body.error === "Bad Request", "error is not Bad Request")
        client.assert(response.body.message === "Поле order должно быть одним из [asc desc].", "wrong message")
    })
%}

### products list
POST {{baseUrl}}/models-v2/{{product-model-code}}/elements/list?offset={{offset}}&limit={{limit}}&sort=sdf&order=sdf
Content-Type: application/json
Service-Code: {{service-code}}
Authorization: {{access}}

{
    "filter": {
        "name": [
            "Продуктовый 24/7",
            "Компуктеры"
        ]
    }
}

> {%
    client.test("Request executed successfully", function () {
        const type = response.contentType.mimeType
        client.assert(type === "application/json", "Expected 'application/json' but received '" + type + "'")
        client.assert(response.status === 400, "Response status is not 400")
        client.assert(response.body.code === 400, "code is not 400")
        client.assert(response.body.error === "Bad Request", "error is not Bad Request")
        client.assert(response.body.message === "Поле order должно быть одним из [asc desc].", "wrong message")
    })
%}

### create strore elements
POST {{baseUrl}}/models-v2/{{product-model-code}}/elements
Content-Type: application/json
Service-Code: {{service-code}}
Authorization: {{access}}

{
    "name": "sdf",
    "externalId": 123,
    "category": "92d5d205-2eda-469d-a265-bb35d8e2f248",
    "colors": [
        "#884535"
    ]
}

> {%
    client.test("Request executed successfully", function () {
        const type = response.contentType.mimeType
        client.assert(type === "application/json", "Expected 'application/json' but received '" + type + "'")
        client.assert(response.status === 201, "Response status is not 201")
        client.assert(response.body.hasOwnProperty("id"), "Body has not property id")
    })
    client.global.set("productElementId", response.body.id)
%}

#### get strore element
#GET {{baseUrl}}/models-v2/{{product-model-code}}/elements/{{productElementId}}
#Service-Code: {{service-code}}
#Authorization: {{access}}
#
#> {%
#    client.test("Request executed successfully", function () {
#        const type = response.contentType.mimeType
#        client.assert(type === "application/json", "Expected 'application/json' but received '" + type + "'")
#        client.assert(response.status === 200, "Response status is not 200")
#        const env = request.environment
#        client.assert(response.body.id == client.global.get("productElementId"), "Element identifier is not " + client.global.get("productElementId"))
#        client.assert(response.body.name == env.get("product.name"), "Element name is not " + env.get("product.name"))
#        client.assert(response.body.latitude == env.get("product.latitude"), "Element latitude is not " + env.get("product.latitude"))
#        client.assert(response.body.longitude == env.get("product.longitude"), "Element longitude is not " + env.get("product.longitude"))
#        client.assert(response.body.contactEmail == env.get("product.contactEmail"), "Element contactEmail is not " + env.get("product.contactEmail"))
#        client.assert(response.body.contactPhone == env.get("product.contactPhone"), "Element contactPhone is not " + env.get("product.contactPhone"))
#        client.assert(response.body.openingTime == env.get("product.openingTime"), "Element openingTime is not " + env.get("product.openingTime"))
#        client.assert(response.body.closingTime == env.get("product.closingTime"), "Element closingTime is not " + env.get("product.closingTime"))
#    })
#%}
#
#### update product element
#PUT {{baseUrl}}/models-v2/{{product-model-code}}/elements/{{productElementId}}
#Content-Type: application/json
#Service-Code: {{service-code}}
#Authorization: {{access}}
#
#{
#    "name":         "{{product.new.name}}",
#    "latitude":     58.6299,
#    "longitude":    38.8737,
#    "contactEmail": "{{product.new.contactEmail}}",
#    "contactPhone": "{{product.new.contactPhone}}",
#    "openingTime":  "{{product.new.openingTime}}",
#    "closingTime":  "{{product.new.closingTime}}",
#    "description":  "{{product.new.description}}",
#    "products":     ["552f331e-be9e-4c3a-a860-7071fd5fd359"]
#}
#
#> {%
#    client.test("Request executed successfully", function () {
#        client.assert(response.status === 204, "Response status is not 204")
#        client.assert(response.body == null, "Response body is not empty")
#    })
#%}
#
#### get strore element
#GET {{baseUrl}}/models-v2/{{product-model-code}}/elements/{{productElementId}}
#Service-Code: {{service-code}}
#Authorization: {{access}}
#
#> {%
#    client.test("Request executed successfully", function () {
#        const type = response.contentType.mimeType
#        client.assert(type === "application/json", "Expected 'application/json' but received '" + type + "'")
#        client.assert(response.status === 200, "Response status is not 200")
#        const env = request.environment
#        client.assert(response.body.id == client.global.get("productElementId"), "Element identifier is not " + client.global.get("productElementId"))
#        client.assert(response.body.name == env.get("product.new.name"), "Element name is not " + env.get("product.new.name"))
#        client.assert(response.body.latitude == env.get("product.new.latitude"), "Element latitude is not " + env.get("product.new.latitude"))
#        client.assert(response.body.longitude == env.get("product.new.longitude"), "Element longitude is not " + env.get("product.new.longitude"))
#        client.assert(response.body.contactEmail == env.get("product.new.contactEmail"), "Element contactEmail is not " + env.get("product.new.contactEmail"))
#        client.assert(response.body.contactPhone == env.get("product.new.contactPhone"), "Element contactPhone is not " + env.get("product.new.contactPhone"))
#        client.assert(response.body.openingTime == env.get("product.new.openingTime"), "Element openingTime is not " + env.get("product.new.openingTime"))
#        client.assert(response.body.closingTime == env.get("product.new.closingTime"), "Element closingTime is not " + env.get("product.new.closingTime"))
#    })
#%}
#
#### delete strore element
#DELETE {{baseUrl}}/models-v2/{{product-model-code}}/elements/{{productElementId}}
#Service-Code: {{service-code}}
#Authorization: {{access}}
#
#> {%
#    client.test("Request executed successfully", function () {
#        client.assert(response.status === 204, "Response status is not 204")
#        client.assert(response.body == null, "Response body is not empty")
#    })
#%}
#
#### get strore element
#GET {{baseUrl}}/models-v2/{{product-model-code}}/elements/{{productElementId}}
#Service-Code: {{service-code}}
#Authorization: {{access}}
#
#> {%
#    client.test("Request executed successfully", function () {
#        const type = response.contentType.mimeType
#        client.assert(type === "application/json", "Expected 'application/json' but received '" + type + "'")
#        client.assert(response.status === 404, "Response status is not 200")
#    })
#%}

### --------------------------------- END STORES --------------------------------------------

GET https://{{baseUrl}}/models-v2/products/elements?fields=externalId&fields=name&offset=0&limit=20&
    pkeys=552f331e-be9e-4c3a-a860-7071fd5fd359
Service-Code: {{service-code}}
Authorization: {{access}}