### auth
POST https://keycloak.farmperspektiva.aeroidea.ru/auth/realms/Test/protocol/openid-connect/token
Content-Type: application/x-www-form-urlencoded
Accept: application/json

grant_type=password&client_id=focus&client_secret=d5d89a18-e76d-47da-af94-8dafb8c1c250&username={{username}}&password={{password}}

> {%
    client.test("Request executed successfully", function () {
        const type = response.contentType.mimeType
        client.assert(type === "application/json", "Expected 'application/json' but received '" + type + "'")
        client.assert(response.status === 200, "Response status is not 200")
        client.assert(response.body.hasOwnProperty("access_token"), "Dont have access_token")
    })

    client.global.set("access", response.body.access_token)
%}

###
GET    {{baseUrl}}/mail-templates?offset=0&limit=10
Service-Code: {{service-code}}
Authorization: {{access}}

###
POST   {{baseUrl}}/mail-templates
Content-Type: application/json
Service-Code: {{service-code}}
Authorization: {{access}}

{
    "subject": "Оставлено сообщение обратной связи [#RS_FORM_ID#] #RS_FORM_NAME#",
    "sender": "test@mail.ru",
    "recipients": [
        "test@mail.ru"
    ],
    "template": "string"
}

> {%
    client.test("Request executed successfully", function () {
        const type = response.contentType.mimeType
        client.assert(type === "application/json", "Expected 'application/json' but received '" + type + "'")
        client.assert(response.status === 201, "Response status is not 201")
        client.assert(response.body.hasOwnProperty("id"), "Dont have id")
    })

    client.global.set("mail-template-id", response.body.id)
%}

###
DELETE {{baseUrl}}/mail-templates
Service-Code: {{service-code}}
Authorization: {{access}}

###
GET    {{baseUrl}}/mail-templates/{{mail-template-id}}
Service-Code: {{service-code}}
Authorization: {{access}}

###
PUT    {{baseUrl}}/mail-templates/{{mail-template-id}}
Content-Type: application/json
Service-Code: {{service-code}}
Authorization: {{access}}

{
    "subject": "Оставлено сообщение обратной связи [#RS_FORM_ID#] #RS_FORM_NAME#",
    "sender": "test@mail.ru",
    "recipients": [
        "test@mail.ru"
    ],
    "template": "string"
}

###
DELETE {{baseUrl}}/mail-templates/{{mail-template-id}}
Service-Code: {{service-code}}
Authorization: {{access}}
